//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceTokens.WEB.wsServicio {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsServicio.wsClientesSoap")]
    public interface wsClientesSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje AutenticacionUsuarioRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutenticacionUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceTokens.WEB.wsServicio.AutenticacionUsuarioResponse AutenticacionUsuario(WebServiceTokens.WEB.wsServicio.AutenticacionUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutenticacionUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceTokens.WEB.wsServicio.AutenticacionUsuarioResponse> AutenticacionUsuarioAsync(WebServiceTokens.WEB.wsServicio.AutenticacionUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje dsConsultaClientesRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dsConsultaClientes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceTokens.WEB.wsServicio.dsConsultaClientesResponse dsConsultaClientes(WebServiceTokens.WEB.wsServicio.dsConsultaClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dsConsultaClientes", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceTokens.WEB.wsServicio.dsConsultaClientesResponse> dsConsultaClientesAsync(WebServiceTokens.WEB.wsServicio.dsConsultaClientesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsSeguridad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string stTokenField;
        
        private string autenticationTokenField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string stToken {
            get {
                return this.stTokenField;
            }
            set {
                this.stTokenField = value;
                this.RaisePropertyChanged("stToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AutenticationToken {
            get {
                return this.autenticationTokenField;
            }
            set {
                this.autenticationTokenField = value;
                this.RaisePropertyChanged("AutenticationToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AutenticacionUsuario", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AutenticacionUsuarioRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WebServiceTokens.WEB.wsServicio.clsSeguridad clsSeguridad;
        
        public AutenticacionUsuarioRequest() {
        }
        
        public AutenticacionUsuarioRequest(WebServiceTokens.WEB.wsServicio.clsSeguridad clsSeguridad) {
            this.clsSeguridad = clsSeguridad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AutenticacionUsuarioResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AutenticacionUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string AutenticacionUsuarioResult;
        
        public AutenticacionUsuarioResponse() {
        }
        
        public AutenticacionUsuarioResponse(string AutenticacionUsuarioResult) {
            this.AutenticacionUsuarioResult = AutenticacionUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="dsConsultaClientes", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class dsConsultaClientesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WebServiceTokens.WEB.wsServicio.clsSeguridad clsSeguridad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int lnID;
        
        public dsConsultaClientesRequest() {
        }
        
        public dsConsultaClientesRequest(WebServiceTokens.WEB.wsServicio.clsSeguridad clsSeguridad, int lnID) {
            this.clsSeguridad = clsSeguridad;
            this.lnID = lnID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="dsConsultaClientesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class dsConsultaClientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet dsConsultaClientesResult;
        
        public dsConsultaClientesResponse() {
        }
        
        public dsConsultaClientesResponse(System.Data.DataSet dsConsultaClientesResult) {
            this.dsConsultaClientesResult = dsConsultaClientesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsClientesSoapChannel : WebServiceTokens.WEB.wsServicio.wsClientesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsClientesSoapClient : System.ServiceModel.ClientBase<WebServiceTokens.WEB.wsServicio.wsClientesSoap>, WebServiceTokens.WEB.wsServicio.wsClientesSoap {
        
        public wsClientesSoapClient() {
        }
        
        public wsClientesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsClientesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsClientesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsClientesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceTokens.WEB.wsServicio.AutenticacionUsuarioResponse WebServiceTokens.WEB.wsServicio.wsClientesSoap.AutenticacionUsuario(WebServiceTokens.WEB.wsServicio.AutenticacionUsuarioRequest request) {
            return base.Channel.AutenticacionUsuario(request);
        }
        
        public string AutenticacionUsuario(WebServiceTokens.WEB.wsServicio.clsSeguridad clsSeguridad) {
            WebServiceTokens.WEB.wsServicio.AutenticacionUsuarioRequest inValue = new WebServiceTokens.WEB.wsServicio.AutenticacionUsuarioRequest();
            inValue.clsSeguridad = clsSeguridad;
            WebServiceTokens.WEB.wsServicio.AutenticacionUsuarioResponse retVal = ((WebServiceTokens.WEB.wsServicio.wsClientesSoap)(this)).AutenticacionUsuario(inValue);
            return retVal.AutenticacionUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceTokens.WEB.wsServicio.AutenticacionUsuarioResponse> WebServiceTokens.WEB.wsServicio.wsClientesSoap.AutenticacionUsuarioAsync(WebServiceTokens.WEB.wsServicio.AutenticacionUsuarioRequest request) {
            return base.Channel.AutenticacionUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceTokens.WEB.wsServicio.AutenticacionUsuarioResponse> AutenticacionUsuarioAsync(WebServiceTokens.WEB.wsServicio.clsSeguridad clsSeguridad) {
            WebServiceTokens.WEB.wsServicio.AutenticacionUsuarioRequest inValue = new WebServiceTokens.WEB.wsServicio.AutenticacionUsuarioRequest();
            inValue.clsSeguridad = clsSeguridad;
            return ((WebServiceTokens.WEB.wsServicio.wsClientesSoap)(this)).AutenticacionUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceTokens.WEB.wsServicio.dsConsultaClientesResponse WebServiceTokens.WEB.wsServicio.wsClientesSoap.dsConsultaClientes(WebServiceTokens.WEB.wsServicio.dsConsultaClientesRequest request) {
            return base.Channel.dsConsultaClientes(request);
        }
        
        public System.Data.DataSet dsConsultaClientes(WebServiceTokens.WEB.wsServicio.clsSeguridad clsSeguridad, int lnID) {
            WebServiceTokens.WEB.wsServicio.dsConsultaClientesRequest inValue = new WebServiceTokens.WEB.wsServicio.dsConsultaClientesRequest();
            inValue.clsSeguridad = clsSeguridad;
            inValue.lnID = lnID;
            WebServiceTokens.WEB.wsServicio.dsConsultaClientesResponse retVal = ((WebServiceTokens.WEB.wsServicio.wsClientesSoap)(this)).dsConsultaClientes(inValue);
            return retVal.dsConsultaClientesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceTokens.WEB.wsServicio.dsConsultaClientesResponse> WebServiceTokens.WEB.wsServicio.wsClientesSoap.dsConsultaClientesAsync(WebServiceTokens.WEB.wsServicio.dsConsultaClientesRequest request) {
            return base.Channel.dsConsultaClientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceTokens.WEB.wsServicio.dsConsultaClientesResponse> dsConsultaClientesAsync(WebServiceTokens.WEB.wsServicio.clsSeguridad clsSeguridad, int lnID) {
            WebServiceTokens.WEB.wsServicio.dsConsultaClientesRequest inValue = new WebServiceTokens.WEB.wsServicio.dsConsultaClientesRequest();
            inValue.clsSeguridad = clsSeguridad;
            inValue.lnID = lnID;
            return ((WebServiceTokens.WEB.wsServicio.wsClientesSoap)(this)).dsConsultaClientesAsync(inValue);
        }
    }
}
